spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: yqxxnaxr1109

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

page:
  topTitle: ログイン
  topUrl: /top

board:
  title:
    top: ログイン
    topUrl: /top
    main: 掲示板
    mainUrl: /main
    register: 新規登録
    registerUrl: /register